name: Deploy to EC2 
on: 
  push: 
    branches: [ "main" ]  
    paths:
      - 'front/**'
jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout del código 
        uses: actions/checkout@v4 

      - name: Copiar a carpeta temporal 
        uses: appleboy/scp-action@v0.1.7 

        with: 
          host: ${{ secrets.EC2_FRONT_HOST }} 
          username: ${{ secrets.EC2_API_USER }} 
          key: ${{ secrets.EC2_API_SSH_KEY }} 
          source: "." 
          target: "/home/ubuntu/web-temp" # Carpeta con permiso 
      - name: Mover a carpeta de apache 
        uses: appleboy/ssh-action@v1.0.3 

        with: 
          host: ${{ secrets.EC2_FRONT_HOST }} 
          username: ${{ secrets.EC2_API_USER }} 
          key: ${{ secrets.EC2_API_SSH_KEY }} 
          script: | 
            sudo cp -r /home/ubuntu/web-temp/* /var/www/html/ 
            sudo rm -rf /home/ubuntu/web-temp/* 