name: Deploy to EC2 
on: 
  push: 
    branches: [ "main" ]  
    paths:
      - 'front/**'

jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout del código 
        uses: actions/checkout@v4 

      - name: Copiar frontend a carpeta temporal 
        uses: appleboy/scp-action@v0.1.7 
        with: 
          host: ${{ secrets.EC2_FRONT_HOST }} 
          username: ${{ secrets.EC2_API_USER }} 
          key: ${{ secrets.EC2_API_SSH_KEY }} 
          # 1. Cambiamos el origen para que SOLO apunte a la carpeta front
          source: "front/**" 
          target: "/home/ubuntu/web-temp" 
          # 2. Esto evita que se cree la estructura de carpetas "front/" dentro del destino
          strip_components: 1 

      - name: Mover a carpeta de apache 
        uses: appleboy/ssh-action@v1.0.3 
        with: 
          host: ${{ secrets.EC2_FRONT_HOST }} 
          username: ${{ secrets.EC2_API_USER }} 
          key: ${{ secrets.EC2_API_SSH_KEY }} 
          script: | 
            # 3. Limpiamos Apache antes para no dejar basura del deploy incorrecto anterior
            sudo rm -rf /var/www/html/*
            # 4. Movemos el contenido limpio
            sudo cp -r /home/ubuntu/web-temp/* /var/www/html/ 
            sudo rm -rf /home/ubuntu/web-temp/*